<?php
//
//for($i = -50; $i <= 50; ++$i) {
//    print "$i<br>";
//}

?>
<table>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Symfony\Component\Debug\Exception\ContextErrorException: Notice: Undefined index: entity_id in /home/will/Sites/forgely/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line <i>2744</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0115</td><td bgcolor='#eeeeec' align='right'>239584</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/home/will/Sites/forgely/web/app_dev.php' bgcolor='#eeeeec'>.../app_dev.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.1626</td><td bgcolor='#eeeeec' align='right'>3086816</td><td bgcolor='#eeeeec'>Symfony\Component\HttpKernel\Kernel->handle( ???, ???, ??? )</td><td title='/home/will/Sites/forgely/web/app_dev.php' bgcolor='#eeeeec'>.../app_dev.php<b>:</b>21</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.3675</td><td bgcolor='#eeeeec' align='right'>14924144</td><td bgcolor='#eeeeec'>Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle( ???, ???, ??? )</td><td title='/home/will/Sites/forgely/app/bootstrap.php.cache' bgcolor='#eeeeec'>.../bootstrap.php.cache<b>:</b>2540</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.3676</td><td bgcolor='#eeeeec' align='right'>14925888</td><td bgcolor='#eeeeec'>Symfony\Component\HttpKernel\HttpKernel->handle( ???, ???, ??? )</td><td title='/home/will/Sites/forgely/app/bootstrap.php.cache' bgcolor='#eeeeec'>.../bootstrap.php.cache<b>:</b>3335</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.3677</td><td bgcolor='#eeeeec' align='right'>14926840</td><td bgcolor='#eeeeec'>Symfony\Component\HttpKernel\HttpKernel->handleRaw( ???, ??? )</td><td title='/home/will/Sites/forgely/app/bootstrap.php.cache' bgcolor='#eeeeec'>.../bootstrap.php.cache<b>:</b>3181</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>5.5358</td><td bgcolor='#eeeeec' align='right'>27419784</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.call-user-func-array:{/home/will/Sites/forgely/app/bootstrap.php.cache:3222}' target='_new'>call_user_func_array:{/home/will/Sites/forgely/app/bootstrap.php.cache:3222}</a>
        ( ???, ??? )</td><td title='/home/will/Sites/forgely/app/bootstrap.php.cache' bgcolor='#eeeeec'>.../bootstrap.php.cache<b>:</b>3222</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>5.5358</td><td bgcolor='#eeeeec' align='right'>27422184</td><td bgcolor='#eeeeec'>Coalmarch\Forgely\RestBundle\Controller\DashboardController->getTilesAction(  )</td><td title='/home/will/Sites/forgely/app/bootstrap.php.cache' bgcolor='#eeeeec'>.../bootstrap.php.cache<b>:</b>3222</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>8</td><td bgcolor='#eeeeec' align='center'>11.5174</td><td bgcolor='#eeeeec' align='right'>28659536</td><td bgcolor='#eeeeec'>Coalmarch\Forgely\CoreBundle\Entity\EnrollmentRepository->findTodoByEmployee( ???, ???, ??? )</td><td title='/home/will/Sites/forgely/src/Coalmarch/Forgely/RestBundle/Controller/DashboardController.php' bgcolor='#eeeeec'>.../DashboardController.php<b>:</b>32</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>9</td><td bgcolor='#eeeeec' align='center'>11.5322</td><td bgcolor='#eeeeec' align='right'>29204720</td><td bgcolor='#eeeeec'>Doctrine\ORM\AbstractQuery->getResult( ??? )</td><td title='/home/will/Sites/forgely/src/Coalmarch/Forgely/CoreBundle/Entity/EnrollmentRepository.php' bgcolor='#eeeeec'>.../EnrollmentRepository.php<b>:</b>1255</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>10</td><td bgcolor='#eeeeec' align='center'>11.5322</td><td bgcolor='#eeeeec' align='right'>29204896</td><td bgcolor='#eeeeec'>Doctrine\ORM\AbstractQuery->execute( ???, ??? )</td><td title='/home/will/Sites/forgely/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php' bgcolor='#eeeeec'>.../AbstractQuery.php<b>:</b>727</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>11</td><td bgcolor='#eeeeec' align='center'>11.5322</td><td bgcolor='#eeeeec' align='right'>29205160</td><td bgcolor='#eeeeec'>Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache( ???, ??? )</td><td title='/home/will/Sites/forgely/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php' bgcolor='#eeeeec'>.../AbstractQuery.php<b>:</b>924</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>12</td><td bgcolor='#eeeeec' align='center'>11.6272</td><td bgcolor='#eeeeec' align='right'>30469272</td><td bgcolor='#eeeeec'>Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll( ???, ???, ??? )</td><td title='/home/will/Sites/forgely/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php' bgcolor='#eeeeec'>.../AbstractQuery.php<b>:</b>978</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>13</td><td bgcolor='#eeeeec' align='center'>11.6470</td><td bgcolor='#eeeeec' align='right'>30721144</td><td bgcolor='#eeeeec'>Doctrine\ORM\Internal\Hydration\ObjectHydrator->cleanup(  )</td><td title='/home/will/Sites/forgely/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php' bgcolor='#eeeeec'>.../AbstractHydrator.php<b>:</b>149</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>14</td><td bgcolor='#eeeeec' align='center'>11.6470</td><td bgcolor='#eeeeec' align='right'>30702408</td><td bgcolor='#eeeeec'>Doctrine\ORM\UnitOfWork->hydrationComplete(  )</td><td title='/home/will/Sites/forgely/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php' bgcolor='#eeeeec'>.../ObjectHydrator.php<b>:</b>154</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>15</td><td bgcolor='#eeeeec' align='center'>11.6470</td><td bgcolor='#eeeeec' align='right'>30702408</td><td bgcolor='#eeeeec'>Doctrine\ORM\Internal\HydrationCompleteHandler->hydrationComplete(  )</td><td title='/home/will/Sites/forgely/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php' bgcolor='#eeeeec'>.../UnitOfWork.php<b>:</b>3478</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>16</td><td bgcolor='#eeeeec' align='center'>11.6874</td><td bgcolor='#eeeeec' align='right'>31137160</td><td bgcolor='#eeeeec'>Doctrine\ORM\Event\ListenersInvoker->invoke( ???, ???, ???, ???, ??? )</td><td title='/home/will/Sites/forgely/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/HydrationCompleteHandler.php' bgcolor='#eeeeec'>.../HydrationCompleteHandler.php<b>:</b>100</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>17</td><td bgcolor='#eeeeec' align='center'>11.6874</td><td bgcolor='#eeeeec' align='right'>31137160</td><td bgcolor='#eeeeec'>Symfony\Bridge\Doctrine\ContainerAwareEventManager->dispatchEvent( ???, ??? )</td><td title='/home/will/Sites/forgely/vendor/doctrine/orm/lib/Doctrine/ORM/Event/ListenersInvoker.php' bgcolor='#eeeeec'>.../ListenersInvoker.php<b>:</b>117</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>18</td><td bgcolor='#eeeeec' align='center'>11.6874</td><td bgcolor='#eeeeec' align='right'>31137312</td><td bgcolor='#eeeeec'>Coalmarch\Forgely\CoreBundle\EventListener\HydrateEnrollmentEntity->postLoad( ??? )</td><td title='/home/will/Sites/forgely/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php' bgcolor='#eeeeec'>.../ContainerAwareEventManager.php<b>:</b>63</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>19</td><td bgcolor='#eeeeec' align='center'>11.6915</td><td bgcolor='#eeeeec' align='right'>31240392</td><td bgcolor='#eeeeec'>Doctrine\ORM\EntityRepository->findOneBy( ???, ??? )</td><td title='/home/will/Sites/forgely/src/Coalmarch/Forgely/CoreBundle/EventListener/HydrateEnrollmentEntity.php' bgcolor='#eeeeec'>.../HydrateEnrollmentEntity.php<b>:</b>21</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>20</td><td bgcolor='#eeeeec' align='center'>11.6916</td><td bgcolor='#eeeeec' align='right'>31242192</td><td bgcolor='#eeeeec'>Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load( ???, ???, ???, ???, ???, ???, ??? )</td><td title='/home/will/Sites/forgely/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php' bgcolor='#eeeeec'>.../EntityRepository.php<b>:</b>196</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>21</td><td bgcolor='#eeeeec' align='center'>11.7041</td><td bgcolor='#eeeeec' align='right'>31303064</td><td bgcolor='#eeeeec'>Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll( ???, ???, ??? )</td><td title='/home/will/Sites/forgely/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php' bgcolor='#eeeeec'>.../BasicEntityPersister.php<b>:</b>720</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>22</td><td bgcolor='#eeeeec' align='center'>11.7042</td><td bgcolor='#eeeeec' align='right'>31303432</td><td bgcolor='#eeeeec'>Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator->hydrateAllData(  )</td><td title='/home/will/Sites/forgely/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php' bgcolor='#eeeeec'>.../AbstractHydrator.php<b>:</b>147</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>23</td><td bgcolor='#eeeeec' align='center'>11.7042</td><td bgcolor='#eeeeec' align='right'>31305232</td><td bgcolor='#eeeeec'>Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator->hydrateRowData( ???, ??? )</td><td title='/home/will/Sites/forgely/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php' bgcolor='#eeeeec'>.../SimpleObjectHydrator.php<b>:</b>69</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>24</td><td bgcolor='#eeeeec' align='center'>11.7045</td><td bgcolor='#eeeeec' align='right'>31312768</td><td bgcolor='#eeeeec'>Doctrine\ORM\UnitOfWork->createEntity( ???, ???, ??? )</td><td title='/home/will/Sites/forgely/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php' bgcolor='#eeeeec'>.../SimpleObjectHydrator.php<b>:</b>147</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>25</td><td bgcolor='#eeeeec' align='center'>11.7048</td><td bgcolor='#eeeeec' align='right'>31323320</td><td bgcolor='#eeeeec'>Symfony\Component\Debug\ErrorHandler->handleError( ???, ???, ???, ???, ??? )</td><td title='/home/will/Sites/forgely/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php' bgcolor='#eeeeec'>.../SimpleObjectHydrator.php<b>:</b>2744</td></tr>
</table>h coo