#!/usr/bin/env bash

PROJECTDIR="Sites"
if [[ "${PWD}" =~ ^$HOME/Projects ]]; then
    PROJECTDIR="Projects"
fi

if [[ ! "${PWD}" =~ ^$HOME/$PROJECTDIR ]]; then
    echo "Not in a Project directory like ~/Sites or ~/Projects"
    exit 1;
fi

SITE=${PWD##*/$PROJECTDIR/}
SITE=${SITE%%/*}

ROOT=$HOME/$PROJECTDIR/$SITE;

tests=(
  "bin/appc::COALMARCH_SYMPHONY"
  "bin/console::SYMPHONY_4"
  "app/console::SYMPHONY"
  "artisan::LARAVEL"
  "vendor/bin/drupal::DRUPAL_CONSOLE"
  "core/lib/Drupal.php::DRUPAL_8"
  "modules/system/system.module::DRUPAL_7"
  "wp-config.php::WORDPRESS"
);

for index in "${tests[@]}"; do
    dir="${index%%::*}";
    type="${index##*::}";
    testdir=$ROOT/$dir;
    if [ -z $cmd ]; then
        if [ -f $testdir ]; then
            case $type in
            DRUPAL_8)
                cmd="drush";
                ;;
            DRUPAL_7)
                cmd="drush";
                ;;
            WORDPRESS)
                cmd="wp";
                ;;
            *)
                cmd=$testdir;
                ;;
            esac
        fi
    fi
done

if [ -z "$cmd" ]; then
    echo "Not a valid site."
    exit 1;
fi

$cmd "$@";