#!/bin/bash

set -e

if [ -z "$1" ]
then
        SITE=${PWD##*/}
else
        SITE=$1
fi;

if [ -z "$2" ]
then
        ENV="dev"
else
        ENV=$2
fi;

if [ "$SITE" = "live" ] || [ "$SITE" = "dev" ] || [ "$SITE" = "test" ]
then
    ENV=$SITE
    SITE=${PWD##*/}
fi;

notfound="Not found:.*"
if [[ $((drush sa @pantheon.$SITE.$ENV) 2>&1) =~ $notfound ]]
then
    echo "Alias @pantheon.$SITE.$ENV not found!"
    echo "refreshing aliases.."
    terminus sites aliases
fi;

cd ~/Sites/$SITE/sites/default;
drush cc all;
if [ -d "files" ]; then
chmod -R 777 files
fi  
drush -r . -y rsync @pantheon.$SITE.$ENV:%files . --progress;
echo "DONE!"
chmod -R 777 files/;
cd -;
osascript -e "display notification \"Files synced for $SITE\" with title \"Files Synced!\"";
#say "files synced";
