#! /usr/bin/env bash

set -e

DRUSH8=${HOME}/bin/drush8;
DRUSH=${HOME}/drush/vendor/bin/drush;

PROJECTDIR="Sites"
if [[ "${PWD}" =~ ^${HOME}/Projects ]]; then
    PROJECTDIR="Projects"
fi

if [[ ! "${PWD}" =~ ^${HOME}/$PROJECTDIR ]]; then
    DRUPALV=8
else
    SITE=${PWD##*/$PROJECTDIR/}
    SITE=${SITE%%/*}

    if [ -f ~/${PROJECTDIR}/${SITE}/core/lib/Drupal.php ]
    then
        DRUPALV=8
    else
        if [ -f ~/${PROJECTDIR}/${SITE}/modules/system/system.module ]; then
            DRUPALV=7
        else
            DRUPALV=8
        fi;
    fi
fi

if [ $DRUPALV = 8 ]; then
    ##  It doesn't make any sense to use Drush 9 anymore with Pantheon's workflow
    ## We'll stick with drush 8 for now, but I'ma comment out the drush 9 stuff for
    ## Future use
        ${DRUSH8} "$@";
#    INSTALL=0;
##    if [ ! -f ${DRUSH} ]; then
##        INSTALL=1;
##    else
##        VERSION=$($DRUSH version --format=string);
##        VERSION=${VERSION%%.*}
##        if [ ${VERSION} = "8" ]; then
##            rm -rf ${HOME}/drush;
##            INSTALL=1;
##        fi
##    fi
##
##    if [ $INSTALL = 1 ]; then
##        echo "Drush 9 not installed. Installing..."
##        mkdir -p ${HOME}/drush;
##        cd ${HOME}/drush;
##        composer require drush/drush;
##    fi
##
##    ${DRUSH} "$@";
else
    ${DRUSH8} "$@";
fi