#!/bin/bash

set -e

PROJECTDIR="Sites"
if [[ "${PWD}" =~ ^${HOME}/Projects ]]; then
    PROJECTDIR="Projects"
fi

if [ -z "$1" ]
then
    if [[ ! "${PWD}" =~ ^${HOME}/$PROJECTDIR ]]; then
        echo "Not in a Project directory like ~/Sites or ~/Projects"
        exit 1;
    fi

    SITE=${PWD##*/$PROJECTDIR/}
    SITE=${SITE%%/*}
else
    SITE=$1
fi;

if [ -z "$2" ]
then
        ENV="dev"
else
        ENV=$2
fi;

if [ "$SITE" = "live" ] || [ "$SITE" = "dev" ] || [ "$SITE" = "test" ]
then
    ENV=$SITE
    ROOT=$(drush ev "print DRUPAL_ROOT");
    SITE=${ROOT##*/}
fi;

if [ -f ~/Sites/$SITE/core/lib/Drupal.php ]
then
    DRUPALV=8
else
    DRUPALV=7
fi;

notfound="Not found:.*"
if [[ $(drush sa @pantheon.$SITE.$ENV 2>&1) =~ $notfound ]]; then
    echo "Alias @pantheon.$SITE.$ENV not found!"
    echo "refreshing aliases.."
    if [ "$TERMINUS_OLD" = true ]; then
        terminus sites aliases
    else
        terminus aliases
    fi
fi

cd ~/Sites/$SITE/sites/default;
if [ "$DRUPALV" = "7" ]; then
    drush cc all
else
    drush cr
fi
if [ -d "files" ]; then
chmod -R 777 files
fi  
drush -r . -y rsync @pantheon.$SITE.$ENV:%files . --progress;
echo "DONE!"
chmod -R 777 files/;
cd -;
osascript -e "display notification \"Files synced for $SITE\" with title \"Files Synced!\"";
#say "files synced";
