#! /bin/bash

set -e

if [ -z "$1" ]
then
    echo "No file given. Must include a file."
    exit 2
fi;

ROOT=$(drush ev "print DRUPAL_ROOT");
SITE=${ROOT##*/}
SITEROOT=~/Sites/$SITE;
CONTRIB=$SITEROOT/sites/all/modules/contrib

drush sql-create -y &&
pv $1 | gunzip | $(drush sql-connect) &&
drush rr &&
drush dl memcache backup_migrate -y &&
drush dis memcache backup_migrate -y &&
drush pmu memcache backup_migrate -y &&
drush vset cache 0;drush vset preprocess_css 0;drush vset preprocess_js 0 &&
drush cc all &&
rm -rf $CONTRIB/memcache &&
rm -rf $CONTRIB/backup_migrate
