#!/bin/bash

set -e

SCRIPTS="terminus_version
tlogin
terminus-ssp
drushfiles
tclone
siteget
pdeploy
prefresh
pdrush
psftp
rewritebase
createLocalDrupalSettings.sh
getSiteEnv.sh
getscripts
drush
drush8
sprowt-user-add
isSprowt3.sh
addSprowt3Aliases
sqSync.sh
sqSyncCode.sh
sqSyncFiles.sh
sqSyncDB.sh"
mkdir -p ~/bin
cd ~/bin

if [ ! -z ${WILL_SANDBOX_DIR} ]; then
    cd ${WILL_SANDBOX_DIR};
    git pull;
    cd ~/bin
fi

echo '#######################################'
echo '         getting scripts...'
echo '#######################################'
echo
for script in $SCRIPTS;
do
    if [ -f ~/bin/$script ]; then
        rm ~/bin/$script;
    fi

    if [ -z ${WILL_SANDBOX_DIR} ]; then
        echo "Downloading $script to $HOME/bin/$script ..."
        curl https://raw.githubusercontent.com/wmcmillian-coalmarch/wills-repo/master/scripts/$script > $script
        chmod 777 $script
    else
        echo "Linking $script to $HOME/bin/$script ..."
        ln -s ${WILL_SANDBOX_DIR}/scripts/$script ~/bin/
    fi
done

echo
echo '#######################################'
echo '          getting sprowthq-cli'
echo '#######################################'
echo

mkdir -p $HOME/opt;
sqDir="$HOME/opt/sprowthq-cli";
if [ -d $sqDir ]; then
  cd $sqDir && git pull && composer install && $sqDir/bin/console cache:clear;
else
  git clone git@github.com:coalmarch-development/sprowthq-cli.git $sqDir;
  cd $sqDir && composer install && $sqDir/bin/console cache:clear;
fi

rm $HOME/bin/sprowt;
ln -s $sqDir/bin/console $HOME/bin/sprowt;

echo
echo '#######################################'
echo '               DONE!!!'
echo '#######################################'
echo
