#!/bin/bash

SCRIPTS="tlogin
terminus-ssp
drushfiles
tclone
siteget"

cd ~/bin
echo '#######################################'
echo '         getting Scripts...'
echo '#######################################'
echo
for script in $SCRIPTS;
do
    echo "Downloading $script..."
    curl https://raw.githubusercontent.com/wmcmillian-coalmarch/wills-repo/master/scripts/$script > $script
    chmod 777 $script
done

echo
echo '#######################################'
echo '               DONE!!!'
echo '#######################################'
echo
