#!/bin/bash

set -e

SCRIPTS="terminus_version
tlogin
terminus-ssp
drushfiles
tclone
siteget
pdeploy
prefresh
pdrush
psftp
rewritebase
createLocalDrupalSettings.sh
getSiteEnv.sh
getscripts
drush
drush8
sprowt-user-add"
mkdir -p ~/bin
cd ~/bin

if [ ! -z ${WILL_SANDBOX_DIR} ]; then
    cd ${WILL_SANDBOX_DIR};
    git pull;
    cd ~/bin
fi

echo '#######################################'
echo '         getting scripts...'
echo '#######################################'
echo
for script in $SCRIPTS;
do
    if [ -f ~/bin/$script ]; then
        rm ~/bin/$script;
    fi

    if [ -z ${WILL_SANDBOX_DIR} ]; then
        echo "Downloading $script to $HOME/bin/$script ..."
        curl https://raw.githubusercontent.com/wmcmillian-coalmarch/wills-repo/master/scripts/$script > $script
        chmod 777 $script
    else
        echo "Linking $script to $HOME/bin/$script ..."
        ln -s ${WILL_SANDBOX_DIR}/scripts/$script ~/bin/
    fi
done

echo
echo '#######################################'
echo '               DONE!!!'
echo '#######################################'
echo
