#!/bin/bash

if [ "$1" = "--hard" ]
then
    killall -HUP gnome-shell
    exit 0
fi

dbus-send --type=method_call --print-reply --dest=org.gnome.Shell /org/gnome/Shell org.gnome.Shell.Eval string:'global.reexec_self()'