#!/bin/bash

set -e

#if [ -z "$1" ]
#then
#        ROOT=$(drush ev "print DRUPAL_ROOT");
#        SITE=${ROOT##*/}
#else
#        SITE=$1
#fi;

source ${HOME}/bin/getSiteEnv.sh;

 spinner()
    {
        local pid=$1
        local delay=0.5
        local spinstr='|/-\'
        tput civis
        while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
            local temp=${spinstr#?}
            printf " [%c]  " "$spinstr"
            local spinstr=$temp${spinstr%"$temp"}
            sleep $delay
            printf "\b\b\b\b\b\b"
        done
        tput cnorm
        printf "    \b\b\b\b"
    }

    trap 'tput cnorm' EXIT;
printf "Backing up dev..." &&
terminus backup:create $SITE.dev 2>&1 & spinner $!
printf "Backing up test..." &&
terminus backup:create $SITE.test 2>&1 & spinner $!
printf "Backing up live..." &&
terminus backup:create $SITE.live 2>&1 & spinner $!