#!/bin/bash

set -e

if [[ "$1" =~ --.* ]]
then
        SITE=${PWD##*/}
else
        SITE=$1
        shift;
fi;

terminus site deploy --site=$SITE --env=test "$@";
terminus site deploy --site=$SITE --env=live "$@";