#!/bin/bash

set -e;

spinner()
{
    local pid=$1
    local delay=0.75
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}

if [ -z "$1" ]
then
        SITE=${PWD##*/};
else
        SITE=$1
fi;


# Specify the destination folder.
TARGET=$HOME/exports/$SITE;
# Specify the source folder.
SOURCE=~/Sites/$SITE

mkdir -p $TARGET;
touch $TARGET/$SITE-db.sql.gz;
touch $TARGET/$SITE-code.tar.gz
touch $TARGET/$SITE-files.tar.gz
rm $TARGET/$SITE*;

cd $SOURCE;

echo -n "clearing cache..."
drush cc all > /dev/null 2>&1 & spinner $!
echo "cache cleared";

CREDSTR=$(drush sql-connect);
CREDSTR=${CREDSTR#mysql};
CREDSTR=${CREDSTR/--database=/};
CREDS="";

for OPT in $CREDSTR; do
    if [[ $OPT =~ --.* ]]
    then
        CREDS="$CREDS $OPT";
    else
        DB=$OPT;
    fi
done

CREDS="$CREDS $DB";

echo -n "exporting database..."
mysqldump $CREDS | gzip > $TARGET/$SITE-db.sql.gz & spinner $!
echo "exported database to $TARGET/$SITE-db.sql.gz";

echo -n "exporting code..."
tar -czf $TARGET/$SITE-code.tar.gz --exclude=sites/default/files* --exclude=.git* --exclude=.idea* . & spinner $!
echo "exported code to $TARGET/$SITE-code.tar.gz";

echo -n "exporting files..."
cd $SOURCE/sites/default/files
tar -czf $TARGET/$SITE-files.tar.gz . & spinner $!
echo "exported files to $TARGET/$SITE-files.tar.gz";
