#!/bin/bash

set -e
terminus_version

SITENV=$(which getSiteEnv.sh);
source $SITENV;

cd $HOME/Sites/$SITE
if [ "$TERMINUS_OLD" = true ]; then
    terminus site wake --site=$SITE --env=$ENV
else
    terminus env:wake "$SITE.$ENV"
fi
chmod 775 ~/Sites/$SITE/sites/default &&
git pull &&
terminus-ssp $SITE $ENV &&
drushfiles $SITE $ENV