#!/bin/bash

set -e
terminus_version;
if [ "$TERMINUS_OLD" = true ]; then
    echo 'Your Terminus is out of date! Please update!';
    exit 1;
fi

spinner()
{
    local pid=$1
    local delay=0.75
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}

SITE="$1";
CLONE="tclone $SITE"

if [ -z $SITE ]; then
    echo "
        ERROR:

        The first argument must be the site name from pantheon.


        USAGE:

        siteget got-bugs
    "
    exit 1
fi

if [ -n "$2" ]; then
    ENV="$2"
else
    ENV="dev"
fi

cd ~/Sites
tlogin
echo "refreshing site aliases..."

terminus aliases > /dev/null 2>&1 & spinner $!

notfound="Not found:.*"
if [[ $((drush sa @pantheon.$SITE.$ENV) 2>&1) =~ $notfound ]]
then
    echo "Alias @pantheon.$SITE.$ENV not found!"
    echo "adding you to the site in pantheon"
    email=$(terminus auth:whoami);
    terminus site:team:add $SITE $email &&
    echo "refreshing site aliases..."
    terminus aliases > /dev/null 2>&1 & spinner $!
fi;

echo "refreshing site list..."
terminus site:list > /dev/null 2>&1 & spinner $!




if [ -d ~/Sites/$SITE ]; then
    echo "Directory for $SITE already exists. Pulling"
    cd $SITE
    git pull
else
    eval $CLONE &&
    cd $SITE
fi

rewritebase.py $SITE
if [ ! -f sites/default/settings.php ]
then
    DB=${SITE//-/_}
    echo "No settings.php. creating..."
    drush si --db-url=mysqli://root:root@localhost/$DB -y > /dev/null 2>&1
fi;
terminus-ssp $SITE $ENV &&
drushfiles $SITE $ENV &&
cd ~/Sites/$SITE &&
open "http://$SITE.test/"
