#!/bin/bash

set -e
terminus_version;
if [ "$TERMINUS_OLD" = true ]; then
    echo 'Your Terminus is out of date! Please update!';
    exit 1;
fi

spinner()
{
    local pid=$1
    local delay=0.75
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}

SITE="$1";
CLONE="tclone $SITE"

if [ -z $SITE ]; then
    echo "
        ERROR:
        The first argument must be the site name from pantheon.
        USAGE:
        siteget got-bugs
    "
    exit 1
fi

if [ -n "$2" ]; then
    ENV="$2"
else
    ENV="dev"
fi

cd ~/Sites
tlogin
echo "refreshing site aliases..."

terminus aliases > /dev/null 2>&1 & spinner $!

notfound="Not found:.*"
if [[ $((drush sa @pantheon.$SITE.$ENV) 2>&1) =~ $notfound ]]
then
    echo "Alias @pantheon.$SITE.$ENV not found!"
    echo "adding you to the site in pantheon"
    email=$(terminus auth:whoami);
    terminus site:team:add $SITE $email &&
    echo "refreshing site aliases..."
    terminus aliases > /dev/null 2>&1 & spinner $!
fi;
echo "refreshing site list..."
terminus site:list > /dev/null 2>&1 & spinner $!
if [ -d ~/Sites/$SITE ]; then
    echo "Directory for $SITE already exists. Pulling"
    cd $SITE
    chmod 775 ~/Sites/$SITE/sites/default
    git pull
else
    eval $CLONE &&
    cd $SITE
    chmod 775 ~/Sites/$SITE/sites/default
fi
rewritebase $SITE
if [ -f ~/Sites/$SITE/core/lib/Drupal.php ]
then
    DRUPALV=8
else
    DRUPALV=7
fi;
if [ $DRUPALV = "8" ]
then
    DB=${SITE//-/_}
    settings_file=~/Sites/${SITE}/sites/default/settings.php;
    default_settings_file=~/Sites/${SITE}/sites/default/default.settings.php;
    settings_file_tmp=~/Sites/${SITE}/sites/default/settings.php-tmp;
    local_settings=~/Sites/${SITE}/sites/default/settings.local.php;
    local_settings_template=~/Sites/${SITE}/sites/example.settings.local.php;
    install_log=~/Sites/${SITE}/install.log;
    if [ ! -f $local_settings ]; then
        chmod 775 ~/Sites/$SITE/sites/default
        echo "${SITE}/sites/default/settings.local.php not found. Setting up local settings file... This might take a bit...";
        mv $settings_file $settings_file_tmp;
        drush si --db-url=mysql://root:root@localhost/$DB -y > $install_log 2>&1 & spinner $! || true
        if [ -f $settings_file ]; then
            rm $install_log;
            chmod 775 ~/Sites/$SITE/sites/default
            chmod 777 $settings_file;
            cp -f $local_settings_template $local_settings;
            echo "" >> $local_settings;
            echo "" >> $local_settings;
            echo "/**=====================================" >> $local_settings;
            echo "*            local install" >> $local_settings;
            echo "*=====================================**/" >> $local_settings;
            echo "" >> $local_settings;
            echo "" >> $local_settings;
            diff "${default_settings_file}" "${settings_file}" | grep ">" | sed 's/^>//g' | sed 's/^\( *\)\(.\)/\1\1\2/g' >> "${local_settings}";
            rm -f $settings_file;
            mv -f $settings_file_tmp $settings_file;
        else
            echo "Something went wrong...";
            cat $install_log;
            exit 1;
        fi
    fi
    chmod 775 ~/Sites/$SITE/sites/default
else
    if [ ! -f sites/default/settings.php ]
    then
        DB=${SITE//-/_}
        echo "No settings.php. creating..."
        drush si --db-url=mysql://root:root@localhost/$DB -y > /dev/null 2>&1 & spinner $! || true
    fi;
fi;
terminus-ssp $SITE $ENV &&
drushfiles $SITE $ENV &&
cd ~/Sites/$SITE &&
open "http://$SITE.test/"