#!/bin/bash

set -eu
TERMINUS_VERSION=$(terminus --version 2>&1);
pat=".*unknown --version parameter.*"
if [[ "$TERMINUS_VERSION" =~ $pat ]]; then
    TERMINUS_OLD=true;
else
    TERMINUS_OLD=false;
fi

SITE=$1;

if [ "$TERMINUS_OLD" = true ]; then
    UUID=$(terminus site info --site=$SITE --field=id);
else
    UUID=$(terminus site:info $SITE --field=id);
fi

if [ -d ~/Sites/$SITE ]; then
    echo "
        ERROR: ~/Sites/$SITE already exists. You should navigate there and run a git pull.
    "
    exit 1
fi

git clone ssh://codeserver.dev.$UUID@codeserver.dev.$UUID.drush.in:2222/~/repository.git ~/Sites/$SITE;