#!/bin/bash

set -e

terminus_version;

if [ "$1" = "live" ] || [ "$1" = "dev" ] || [ "$1" = "test" ]
then
    ENV=$1;
    shift;
else
    ENV="dev"
fi;

PROJECTDIR="Sites"
if [[ "${PWD}" =~ ^${HOME}/Projects ]]; then
    PROJECTDIR="Projects"
fi

if [ -z "$1" ]
then
    if [[ ! "${PWD}" =~ ^${HOME}/$PROJECTDIR ]]; then
        echo "Not in a Project directory like ~/Sites or ~/Projects"
        exit 1;
    fi

    SITE=${PWD##*/$PROJECTDIR/}
    SITE=${SITE%%/*}
fi
ARGS=""$@"";

if [ "$TERMINUS_OLD" = true ]; then
    terminus drush "$ARGS" --site=$SITE --env=$ENV;
else
    terminus drush $SITE.$ENV "$ARGS"
fi