#!/bin/bash

set -e

terminus_version;

if [ "$1" = "live" ] || [ "$1" = "dev" ] || [ "$1" = "test" ]
then
    ENV=$1;
    shift;
else
    ENV="dev"
fi;

ROOT=$(drush ev "print DRUPAL_ROOT;");
SITE=${ROOT##*/}
ARGS=""$@"";

if [ "$TERMINUS_OLD" = true ]; then
    terminus drush "$ARGS" --site=$SITE --env=$ENV;
else
    terminus drush $SITE.$ENV "$ARGS"
fi