#!/bin/bash

if [ -z "$2" ]
then
        PENV=dev
else
        PENV=$2
fi;

cd ~/Sites/$1/sites/default;
drush @pantheon.$1.$PENV cc all --strict=0;

tlogin

mkdir -p $HOME/sqltemp

terminus site backups create --element=database --site=$1 --env=$PENV
terminus site backups get --element=database --site=$1 --env=$PENV --to=$HOME/sqltemp --latest

drush sql-create -y;

pv ~/sqltemp/$1*.sql.gz | gunzip | $(drush sql-connect);
rm ~/sqltemp/$1*.sql.gz
drush vset cache 0;drush vset preprocess_css 0;drush vset preprocess_js 0;
drush cc all;
cd -;
osascript -e "display notification \"SQL synced for $1\" with title \"SQL synced!\"";
#say "sequel synced";
